### ISSUE TITLE
Wen support for ENS (operation="getResolver",

### ISSUE THREAD

**Issue by johnnieskywalker** [dogechain-lab/dogechain#293]
##I tried to deploy punk.domains to testnet however I failed miserably because of no getResolver support

### Description

npx hardhat run scripts/temp/deployTld.js --network dogechaintestnet
Deploying contracts with the account: 0x497CB171dDF49af82250D7723195D7E47Ca38A95
Account balance: 20000000000000000000
Error: network does not support ENS (operation="getResolver", network="unknown", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)
    at Logger.makeError (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1989:20)
    at step (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'network does not support ENS',
  code: 'UNSUPPORTED_OPERATION',
  operation: 'getResolver',
  network: 'unknown'
}
### Your environment

Linux

### Steps to reproduce

Try to deploy punk-contracts to dogechain testnet, fails with message like above.
### Expected behaviour

I just wanted to deploy this project to dogechain to learn and have some fun. I think it could be cool to have domains on dogechain too.

### Actual behaviour

deployment failed 

### Logs

npx hardhat run scripts/temp/deployTld.js --network dogechaintestnet
Deploying contracts with the account: 0x497CB171dDF49af82250D7723195D7E47Ca38A95
Account balance: 20000000000000000000
Error: network does not support ENS (operation="getResolver", network="unknown", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)
    at Logger.makeError (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1989:20)
    at step (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/home/johnnie/Projects/punk-contracts/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'network does not support ENS',
  code: 'UNSUPPORTED_OPERATION',
  operation: 'getResolver',
  network: 'unknown'
}
### Proposed solution

Make ENS methods available in doge chain maybe ?

**Comment by DarianShawn** [comment]
Dogechain name service is already available on TestNet.
https://twitter.com/DCecosystem/status/1571817814880559104

**Comment by DarianShawn** [comment]
Close it due to long inactivation.
